services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes : 
      - .:/app
    command : npm run dev 


  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cube
      MYSQL_USER: cube
      MYSQL_PASSWORD: cube

      # Donnees persistantes - Pour le CUBE
    volumes:
    - ./docker/db:/var/lib/mysql

  adminer : 
    image : adminer
    ports : 
      - 8080:8080