services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes : 
      - .:/app
    command : npm run dev 


  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cube
      MYSQL_USER: cube
      MYSQL_PASSWORD: cube