name: deploy
run-name: ${{ github.actor }} deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - name: Connect to VM and update repository
        # run : ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ${{ secrets.SSH_KEY }} && cd cesi-devops-test-cdci/ && git pull && npm install && npm run build && pm2 restart all
            # run : 
              ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ${{ secrets.SSH_KEY }} "\
               cd cesi-devops-test-cdci \
               git pull \
                npm install \
                 npm run build \
                  pm2 restart all \"