name: Deploy
run-name: ${{ github.actor }} deploy
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - run : ssh -i ${{ secrets.KEY }} ${{ variables.ADMIN }}@${{ variables.ADMIN }}
      - run : cd cesi-devops-test-cdci/
      - run : git pull
      - run: npm install
      - run: npm run build
      - run: npm run start
      - run: pm2 start npm --name "cesi-devops-test-cdci" -- start
